### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by Talbil** [lingxiaoli94/interactive-hex-meshing#1]
A nice work. 
However, it seems that i got a trouble when clone this project. And the  error is as follows:
Cloning into 'external/eigen'...
remote: A repository for this project does not exist yet.
fatal: repository 'https://gitlab.com/libeigen/eigen.git/' not found

**Comment by lingxiaoli94** [comment]
There appears to be some temporary issue with Eigen on GitLab which should be resolved soon: https://gitlab.com/libeigen/eigen/-/issues/2336.
