### ISSUE TITLE
Error in building

### ISSUE THREAD

**Issue by Liu-Lianger** [lingxiaoli94/interactive-hex-meshing#11]
I can not build the project 'text' successfully, because geomlib.lib(geomlib_generated_generalized_projectiong_cuda.cu.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj

**Comment by IzzakQ** [comment]
Are you build on Windows?

**Comment by Liu-Lianger** [comment]
yes and I fix the problem by adding this to CMakeLists of geomlib

target_compile_definitions(geomlib PRIVATE _DEBUG)
target_compile_definitions(geomlib PRIVATE _DLL)
target_compile_definitions(geomlib PRIVATE _ITERATOR_DEBUG_LEVEL=2)
target_compile_options(geomlib PRIVATE /MDd)

**Comment by IzzakQ** [comment]
you can fix all this code problem, while building, just using chatgpt

**Comment by Liu-Lianger** [comment]
aha! thank you for you advice

**Comment by zyyue99** [comment]
Hello,  I encountered an error “Unable to open input file …\geomlib\Release\geomlib.lib” while building. Could you please tell me how to solve this issue? Thank you very much.

**Comment by Liu-Lianger** [comment]
> Hello, I encountered an error “Unable to open input file …\geomlib\Release\geomlib.lib” while building. Could you please tell me how to solve this issue? Thank you very much.

the error is linking process?

**Comment by zyyue99** [comment]
> > Hello, I encountered an error “Unable to open input file …\geomlib\Release\geomlib.lib” while building. Could you please tell me how to solve this issue? Thank you very much.
> 
> the error is linking process?

My project file after cmake does not have the “geomlib.lib” file.

**Comment by Liu-Lianger** [comment]
check two things 1cmake successfully 2build geomlib project first

**Comment by Liu-Lianger** [comment]
> > > Hello, I encountered an error “Unable to open input file …\geomlib\Release\geomlib.lib” while building. Could you please tell me how to solve this issue? Thank you very much.
> > 
> > 
> > the error is linking process?
> 
> My project file after cmake does not have the “geomlib.lib” file.

check two things 1cmake successfully 2build geomlib project first

**Comment by Liu-Lianger** [comment]
> > > > Hello, I encountered an error “Unable to open input file …\geomlib\Release\geomlib.lib” while building. Could you please tell me how to solve this issue? Thank you very much.
> > > 
> > > 
> > > the error is linking process?
> > 
> > 
> > My project file after cmake does not have the “geomlib.lib” file.
> 
> check two things 1cmake successfully 2build geomlib project first

any other questions you can email 2495980689@qq.com

**Comment by zyyue99** [comment]
> > > > > Hello, I encountered an error “Unable to open input file …\geomlib\Release\geomlib.lib” while building. Could you please tell me how to solve this issue? Thank you very much.
> > > > 
> > > > 
> > > > the error is linking process?
> > > 
> > > 
> > > My project file after cmake does not have the “geomlib.lib” file.
> > 
> > 
> > check two things 1cmake successfully 2build geomlib project first
> 
> any other questions you can email [2495980689@qq.com](mailto:2495980689@qq.com)

Thank you very much for your reply. I will continue to make some attempts.
