### ISSUE TITLE
LFS bandwidth is used up.

### ISSUE THREAD

**Issue by Drunkar** [lingxiaoli94/interactive-hex-meshing#2]
Thank you for your great project.
When I tried to clone this repo, it failed due to the LFS limit:

```
This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

Do you have any storage to upload large files (ex. cloud drive) or any points of contact for funding for the hosting(ex. Paypal, Patreon, Gumroad, etc)?
It's a great project and I'd like to try it out, and I think it's a shame that a way to make it more widely known is being closed off.

**Comment by lingxiaoli94** [comment]
Hi, thanks for bringing up this issue. I did not realize downloading LFS files counts towards the LFS bandwidth quota of the repository owner. I just removed LFS from this repo and moved the large zip file to Dropbox instead (the only file affected being results.zip which contains results; it's now at https://www.dropbox.com/s/kv4ojktq95ptw89/results.zip?dl=0).
