### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by SC-One** [lingxiaoli94/interactive-hex-meshing#9]
when I'm running the application ( `./hex`), I'm facing this error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Ugh!
```

**Comment by Mahdidaeidaei** [comment]
Same! did you find a solution?
I am curious to know if anyone had ever launched this code correctly.

**Comment by SC-One** [comment]
> Same! did you find a solution? I am curious to know if anyone had ever launched this code correctly.

Yeah, I found few solutions but it's not general and for any system it should be checked on system and solve it.
